services:
  - type: web
    name: duck-spam-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PORT
        value: 5000